// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7zVJCPP2-JeLEVBzvM-q_5dJTYkhr044',
    appId: '1:663604262305:web:977d07a72b298e2deec7e0',
    messagingSenderId: '663604262305',
    projectId: 'fitconnect-38ef3',
    authDomain: 'fitconnect-38ef3.firebaseapp.com',
    storageBucket: 'fitconnect-38ef3.appspot.com',
    measurementId: 'G-TPQME6JGWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb_qr-zqPJGQc0T8m15BH8Ul8RCnSoli0',
    appId: '1:663604262305:android:5e24c34bbeda9d9eeec7e0',
    messagingSenderId: '663604262305',
    projectId: 'fitconnect-38ef3',
    storageBucket: 'fitconnect-38ef3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxDLbQmyILwjpVqCTJHQDwLqTCDks-pzw',
    appId: '1:663604262305:ios:b8fcb7d1476b5a4feec7e0',
    messagingSenderId: '663604262305',
    projectId: 'fitconnect-38ef3',
    storageBucket: 'fitconnect-38ef3.appspot.com',
    iosClientId: '663604262305-83emuf4983ltvvt7c6hd36n6erufjflo.apps.googleusercontent.com',
    iosBundleId: 'com.example.fit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxDLbQmyILwjpVqCTJHQDwLqTCDks-pzw',
    appId: '1:663604262305:ios:b8fcb7d1476b5a4feec7e0',
    messagingSenderId: '663604262305',
    projectId: 'fitconnect-38ef3',
    storageBucket: 'fitconnect-38ef3.appspot.com',
    iosClientId: '663604262305-83emuf4983ltvvt7c6hd36n6erufjflo.apps.googleusercontent.com',
    iosBundleId: 'com.example.fit',
  );
}
